# Generated by Django 3.0.8 on 2020-07-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmember',
            name='email',
            field=models.EmailField(default='examples@gmail.com', max_length=100, verbose_name='유저메일'),
            preserve_default=False,
        ),
    ]
