# Generated by Django 3.0.8 on 2020-07-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='태그')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
            ],
            options={
                'verbose_name': '게시판태그',
                'verbose_name_plural': '게시판태그',
                'db_table': 'tags',
            },
        ),
    ]
